posts/urls.py
from django.conf.urls import url
from .autocomplete import CountryAutocomplete

from . import views

urlpatterns = [

    url(r'^create/$', views.post_create, name="create"),
    url(r'^(?P<id>[0-9]+)/$', views.post_detail, name="detail"),
    url(r'^(?P<date>\d{4}-\d{2}-\d{2})/$', views.post_list, name="list-filtered"),
    url(r'^$', views.post_list, name="list"),
    url(r'^(?P<id>[0-9]+)/edit/$', views.post_update, name="update"),
    url(r'^(?P<id>[0-9]+)/delete/$', views.post_delete, name="delete"),
    url(r'get-weather$', views.get_weather, name="get-weather"),
    url(r'read-xml$', views.read_xml, name="read-xml"),
    url(r'aggregate-countries$', views.aggregate_countries, name='aggregate_countries'),
    url(r'annotate$', views.annotate, name='annotate'),
    url(r'get-country/(?P<id>[0-9]+)/$', views.get_country, name='get_country'),

    # Autocomplete
    url(r'^country-autocomplete/$', CountryAutocomplete.as_view(),  name='country-autocomplete',)

]

project3/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', register_view, name="register"),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^verify/(?P<uuid>[a-z0-9\-]+)/', verify, name='verify'),
    url(r'^', include('posts.urls', namespace='posts')),
    url(r'^class-based-views/', include('class_based_views.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import ArrayField


# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    information_correct = models.BooleanField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False )
    start_date = ArrayField(models.DateField(), null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id)
        return qs


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # post = models.ForeignKey(Post)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = CommentManager()

    def __str__(self):
        return str(self.user.email)


class Country(models.Model):
    text = models.CharField(verbose_name='Country', max_length=500, blank=True, null=True)
    population = models.IntegerField(verbose_name='Population', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="Creation date", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Update date", auto_now=True)

    def __str__(self):
        return self.text

    @classmethod
    def country_creator(cls, data):
        text, population = data
        country = cls(text=text, population=population)
        country.save()
        return country


class City(models.Model):
    name = models.CharField(verbose_name='City', max_length=100)
    population = models.IntegerField(verbose_name='population', blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name='Country', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class UserPhone(models.Model):
    user = models.ForeignKey('accounts.User')
    code = models.CharField(verbose_name="Code", max_length=10, blank=True, null=True)
    number = models.CharField(verbose_name="Number", max_length=50, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="Creation date", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Update date", auto_now=True)

    def __str__(self):
        return str(self.number)

posts/forms.py
from django import forms
from .models import Post, Comment
import datetime


class PostForm(forms.ModelForm):
    # title = forms.ModelChoiceField(queryset=Post.objects.all().order_by("title"))
    title = forms.CharField(error_messages={'required': 'You have to fill in this filed'})
    information_correct = forms.BooleanField(required=True)
    start_date = forms.MultipleChoiceField(choices=(('2019-01-01', '2019-01-01'), ('2019-01-01', '2019-02-01')))

    class Meta:
        model = Post
        fields = ["title", "information_correct", "content", "image", "start_date"]

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if not title and not content:
            raise forms.ValidationError('You have to write something!')
        return cleaned_data

    def clean_image(self):
        image = self.cleaned_data['image']
        if image is None:
            raise forms.ValidationError('You have to upload a picture')
        return image


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea)

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Sum, Min, Max, Avg, Count
from itertools import chain
from collections import Counter
import datetime
from .models import Post, Comment, Country, City
from .forms import PostForm, CommentForm
from .decorators import superuser_only, user_is_post_author
from django.contrib.contenttypes.models import ContentType
import csv
import os
from django.conf import settings
from matplotlib import pyplot as plt
import six
from django.forms.models import model_to_dict



def post_list(request, date=None):
    if date:
        if 'q' in request.GET:
            query = request.GET.get('q')
            date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
            posts_list = Post.objects.filter(Q(timestamp__month=date.month), Q(timestamp__year=date.year),
                                             Q(title__icontains=query) | Q(content__contains=query)).order_by('-timestamp')
            '''Look for q in comments'''
            posts_with_comments = Post.objects.filter(Q(timestamp__month=date.month), Q(timestamp__year=date.year),
                                                        comment__content__icontains=query).order_by('-timestamp')
            '''Exclude multiple posts'''
            posts_list = set(list(chain(posts_list, posts_with_comments)))
            posts_list = sorted(posts_list, key=lambda x: x.timestamp, reverse=True)
        else:
            date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
            posts_list = Post.objects.filter(timestamp__month=date.month,
                                             timestamp__year=date.year).order_by("-timestamp")
    else:
        if 'q' in request.GET:
            query = request.GET.get('q')
            posts_list = Post.objects.filter(Q(title__icontains=query) | Q(content__contains=query)).order_by('-timestamp')
            '''Look for q in comments'''
            posts_with_comments = Post.objects.filter(comment__content__icontains=query).order_by('-timestamp')
            '''Exclude multiple posts'''
            posts_list = set(list(chain(posts_list, posts_with_comments)))
            posts_list = sorted(posts_list, key=lambda x: x.timestamp, reverse=True)
        else:
            posts_list = Post.objects.all().order_by("-timestamp")
    paginator = Paginator(posts_list, 5)
    '''
     Convert datetime object to str '2018-06-01'
     then convert this str to  datetime object '2018-06-01'
    '''
    year_month = []
    posts_timestamps = Post.objects.values_list('timestamp', flat=True).order_by('-timestamp')
    for date in posts_timestamps:
        new_date = date.strftime('%Y-%m')
        new_date_object = datetime.datetime.strptime(new_date, "%Y-%m").date()
        year_month.append(new_date_object)
    """
    Counter - counts number of post occurrences in year_month list
    then make list with tuples [(date(year, month, 1), number of posts)]
    which is number of posts for specific year-month
    """
    unique_year_month = reversed(sorted(list(Counter(year_month).items())))

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:

        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "post_list.html", locals())


# @login_required(login_url='/login/')
@superuser_only
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "The post was successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())
    return render(request, "post_form.html", locals())


def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    comments = instance.comments

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        new_comment, created = Comment.objects.get_or_create(
                                    user=request.user,
                                    content_type=content_type,
                                    object_id=obj_id,
                                    content=content_data
                                   )
        return redirect("posts:detail", id=instance.id)
    return render(request, "post_detail.html", locals())


# @login_required(login_url='/login/')
@user_is_post_author
def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "The post was successfully updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    return render(request, "post_form.html", locals())


@user_is_post_author
def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "The post was deleted")
    return redirect("posts:list")


def get_weather(request):
    filename = os.path.join(settings.MEDIA_ROOT, 'weather.csv')
    with open(filename) as f:
        reader = csv.reader(f)
        header_row = next(reader)
        highs = []
        for row in reader:
            highs.append(row[1])
        # fig = plt.figure(dpi=128, figsize=(10, 6))
        plt.plot(highs, c='red')
        plt.title("Daily high temperatures, July 2014", fontsize=24)
        plt.xlabel('', fontsize=16)
        plt.ylabel("Temperature (F)", fontsize=16)
        plt.tick_params(axis='both', which='major', labelsize=16)
        # plt.show()
        plt.savefig(os.path.join(settings.MEDIA_ROOT, 'graphic.jpg'))
        image_path = os.path.join("/media/", "graphic.jpg")
        return render(request, 'graphic.html', {'image_path': image_path})


def read_xml(request):
    import xml.etree.ElementTree as et
    file = os.path.join(settings.MEDIA_ROOT, 'planes.xml')
    tree = et.ElementTree(file=file)
    root = tree.getroot()
    print(root.tag)
    planes = []
    for child in root:
        print('tag:', child.tag)
        plane = {}
        for grandchild in child:
            print('\ttag:', grandchild.tag, grandchild.text)
            plane.update({grandchild.tag: grandchild.text})
        planes.append(plane)
    return render(request, 'planes.html', locals())


def aggregate_countries(request):
    sum_min_population = Country.objects.aggregate(Sum('population'), Min('population'))
    result = Country.objects.aggregate(average_pop=Avg('population'))
    return render(request, 'aggregate_countries.html', locals())


def annotate(request):
    countries = Country.objects.annotate(num_cities=Count('city'))
    print(countries[1].num_cities)

    qss = City.objects.all().values('country__text')

    print(qss)

    # Number of cities with x country
    qs = City.objects.all().values('country__text').annotate(number_of_cities=Count('country__text'))

    print(qs)

    return render(request, 'annotate.html', locals())


def get_country(request, id):
    try:
        post = Country.objects.get(id=id)
    except Country.DoesNotExist:
        return JsonResponse('Nothing', safe=False)
    else:
        return JsonResponse(model_to_dict(post))

templates/add_comment.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}


    <h1>{{ title }}</h1>
    <form method="POST" action="" class="post-form" enctype="multipart/form-data" novalidate="novalidate">
        {% csrf_token %}
        {%  bootstrap_form form %}
        <input type="submit" value="{{ title }}">
    </form>


{% endblock %}

templates/aggregate_countries.html
{% extends 'base.html' %}


{% block content %}

    {{ sum_population }}
    {{ result.average_pop }}


{% endblock %}

templates/annotate.html
{% extends 'base.html' %}


{% block content %}


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'posts/bootstrap/css/bootstrap.min.css' %}">

    <script src="{% static 'js/jquery.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <link rel="stylesheet" href="{% static 'posts/blog.css' %}">
</head>
<body>

{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li class ="message"{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item" href="#">Home</a>
            <a class="blog-nav-item" href="{% url 'posts:list' %}">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                Posts
            </a>
            <a class="blog-nav-item" href="{% url 'posts:create' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add Post
            </a>
            <a class="blog-nav-item pull-right" href="{% url "register" %}"><span
                    class="glyphicon glyphicon-user"></span> Register</a>
            {% if not request.user.is_authenticated %}
                <a class="blog-nav-item pull-right" href="{% url "login" %}">
                    <span class="glyphicon glyphicon-log-in"></span>
                    Login
                </a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <ul class="blog-nav-item pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Welcome, {{ request.user }}</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url "logout" %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
        </nav>
    </div>
</div>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Blog</h1>
        <p class="lead blog-description">blog</p>
    </div>

    <div class="row">

        <div class="col-sm-8 blog-main">

            <div class="blog-post">
                {% block content %}

                {% endblock %}
            </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h4>About</h4>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                    fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>
            <div class="sidebar-module">
                <h4>Archives</h4>
                {# date.0 - month and year; date.1 - number of posts for this month #}
                {% for date in unique_year_month %}
                    {% with date.0 as year_month %}
                        <ol class="list-unstyled">
                            <li>
                                <a href="{% url "posts:list-filtered" year_month %}"> {{ date.0|date:"M Y" }} </a>({{ date.1 }})
                            </li>
                        </ol>
                    {% endwith %}
                {% endfor %}
            </div>
            <div class="sidebar-module">
                <h4>Elsewhere</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </div><!-- /.blog-sidebar -->
    </div><!-- /.row -->

    <footer class="blog-footer">
        <p>2018</p>
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>
</div>
<script src="{% static 'posts/bootstrap/js/bootstrap.min.js' %}"
        ></script>
<script>
    $(document).ready(function () {
        $('ul li.dropdown').hover(function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(200);
        }, function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(200);
        });
    });
</script>
</body>
</html>

templates/graphic.html
{% extends 'base.html' %}


{% block content %}

<h1> Graphic</h1>

<img src="{{ image_path }}">


{% endblock %}

templates/login_form.html
{% extends 'base.html' %}
{% load bootstrap3 staticfiles %}

{% block content %}

    <h1>{{ title }}</h1>
    <form method="POST" action="" class="post-form" enctype="multipart/form-data" novalidate="novalidate">
        {% csrf_token %}
        {% bootstrap_field form.email  %}
        {% bootstrap_field form.password  %}
        <input type="submit" value="{{ title }}">
    </form>

{% endblock %}

templates/planes.html
{% extends 'base.html' %}

{% block content %}
    <h1> Planes</h1>
    <ul>
        {% for plane in planes %}
            <li>Year: {{ plane.year }}, Color: {{ plane.color }}, Model: {{ plane.model }}, Make: {{ plane.make }} </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    {% if request.user.is_superuser %}
        <a class="btn btn-info" href="{% url 'posts:update' instance.id %}">Edit post</a>
        <a class="btn btn-danger" href="{% url 'posts:delete' instance.id %}">Delete post</a>
    {% endif %}
    <p></p>
    {% if instance.image %}
        <img style="width:800px; height:400px" src="{{ instance.image.url }}" class="img-responsive"/>
    {% endif %}

    <h1>{{ instance.title }}</h1>
    <p>{{ instance.content }}</p>
    <p>Author: {{ instance.user }}</p>

    <div>
        <h1>Comments</h1>
        <form method="POST" action="" class="post-form" enctype="multipart/form-data" novalidate="novalidate">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Submit">
        </form>

        <div class="panel panel-default">
            <div class="panel-body">
                {% for comment in comments %}
                    <div class="">
                        <div class="">{{ comment.timestamp }}</div>
                        <strong>{{ comment.user }}</strong>
                        <p>{{ comment.content|linebreaks }}</p>
                        <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/post_form.html
{% extends 'base.html'  %}

{% load bootstrap3 %}


{% block content %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}


<form novalidate="novalidate" method = "POST" action="" class = "post-form"  enctype="multipart/form-data">
 {% csrf_token %}
 {% bootstrap_form form %}
  <input type = "submit" value = "Create Post">
</form>

<script>
$(document).ready(function() {
    $('#id_start_date').select2();
});
</script>


{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% load posts_extras %}


{% block content %}

    <form method="GET">
        <input name="q" value="{{ request.GET.q }}" placeholder="search">
        <button class="btn btn-success" type="submit">
            Search
        </button>
    </form>

    <p>There are {% total_posts %} posts</p>

    {% for post in posts %}

        <div class="blog-post">
            <h2 class="blog-post-title">{{ post.title|huilovanie }}</h2>
            <p class="blog-post-meta">{{ post.timestamp| timesince }} ago <a
                    href="{{ post.get_absolute_url }}">{{ post.user }}</a></p>
            {% if post.image %}
                <img style="width:400px; height:250px" src="{{ post.image.url }}" class="img-responsive"/>
            {% endif %}
            <p>{{ post.content | truncatechars:200 }}</p>
            <p><a class="btn btn-primary btn-lg" href="{{ post.get_absolute_url }}" role="button">Learn more</a></p>
        </div><!-- /.blog-post -->


    {% endfor %}

    <div class="pagination">
    <span class="step-links">
     <ul class="pager">
        {% if posts.has_previous %}
            <li> <a href="?page={{ posts.previous_page_number }}">previous</a></li>
        {% endif %}

         <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

         {% if posts.has_next %}
             <li> <a href="?page={{ posts.next_page_number }}">next</a></li>
         {% endif %}
     </ul>
    </span>
    </div>
    <button id="download">Download file</button>
    <script>
        $(document).ready(function () {
            $("#download").click(function () {
                window.location.href = location.origin + '/media/2018-calendar.xlsx'
            });
        });
    </script>


{% endblock %}

templates/registration_form.html
{% extends 'base.html' %}
{% load bootstrap3 staticfiles %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="POST" action="" class="post-form" enctype="multipart/form-data" novalidate="novalidate">
        {% csrf_token %}
        {% bootstrap_field form.email %}
        {% bootstrap_field form.email2 %}
        {% bootstrap_field form.password %}
        {% bootstrap_field form.country %}
        {% bootstrap_field form.birth_date %}

        <h3>User phones </h3>
        {{ formset.management_form }}
        <div class="wrapper">
            <div class="hide_phone" style="margin-bottom: 10px">
                {{ formset.empty_form.code.label }}
                {{ formset.empty_form.code }}
                {{ formset.empty_form.number.label }}
                {{ formset.empty_form.number }}
                <a href="#" class="close remove" style="color: red">Delete</a>
            </div>

            {% for form in formset %}
                <div class="myform phone phone-container" style="margin-bottom: 10px">
                    {{ form.code.label }}
                    {{ form.code }}
                    {{ form.number.label }}
                    {{ form.number }}
                </div>
                <a href="#" class="remove"></a>
            {% endfor %}

            <a href="#" class="add_form phone" style="color: #3875d7">Add</a>
        </div>
        <input type="submit" value="{{ title }}">
    </form>
    {{ form.media }}

    <script type="text/javascript">

        function add_form(prefix) {
            var input_total_forms = $('input[name="' + prefix + '-TOTAL_FORMS"]');

            var col_forms = input_total_forms.attr("value");
            $('input[name="' + prefix + '-TOTAL_FORMS"]').attr("value", parseInt(col_forms) + 1)
            $('input[name="' + prefix + '-INITIAL_FORMS"]').attr("value", parseInt(col_forms) + 1)
            var new_div = $('div.hide_' + prefix).clone(true).get(0);
            $(new_div).attr("class", "myform " + prefix)

            $(new_div).find('input').each(function () {
                var name = $(this).attr("name").split('-')[2];
                $(this).attr("name", prefix + "-" + parseInt(col_forms) + "-" + name);
                $(this).attr("id", "id_" + prefix + "-" + parseInt(col_forms) + "-" + name);

            });

            $(new_div).find('textarea').each(function () {
                var name = $(this).attr("name").split('-')[2];
                $(this).attr("name", prefix + "-" + parseInt(col_forms) + "-" + name);
                $(this).attr("id", "id_" + prefix + "-" + parseInt(col_forms) + "-" + name);

            });

            $(new_div).find('select').each(function () {
                var name = $(this).attr("name").split('-')[2];
                $(this).attr("name", prefix + "-" + parseInt(col_forms) + "-" + name);
                $(this).attr("id", "id_" + prefix + "-" + parseInt(col_forms) + "-" + name);

            })

            if ($("div." + prefix).length) {
                $(new_div).fadeIn('normal').insertAfter($('div.' + prefix + ':last').get(0));
            }
            else {
                $(new_div).fadeIn('normal').insertAfter($('div.hide_' + prefix).get(0));
            }
            return false;
        }

        function delete_form(a, prefix) {
            var el = $(a).parents('div.' + prefix);
            console.log(el);
            el.removeClass(prefix);

            el.fadeOut('normal', function () {
                el.remove();
            });

            /* $(a).parents('div.myform').fadeOut('normal', function() {
                $(a).parents('div.myform').remove()
            }); */

            var form = $("form[name='jq_form']");

            var input_total_forms = $('input[name="' + prefix + '-TOTAL_FORMS"]');
            var col_forms = input_total_forms.attr("value");
            $('input[name="' + prefix + '-TOTAL_FORMS"]').attr("value", parseInt(col_forms) - 1);

            var input_INITIAL_forms = $('input[name="' + prefix + '-INITIAL_FORMS"]');
            var col_INITIAL_forms = input_INITIAL_forms.attr("value");
            $('input[name="' + prefix + '-INITIAL_FORMS"]').attr("value", parseInt(col_forms) - 1);

            var i = 0;
            $('div.' + prefix).each(function () {
                $(this).find('input, select, textarea').each(function () {
                    var name = $(this).attr("name").split('-')[2];
                    $(this).attr("name", prefix + '-' + i + "-" + name);
                    $(this).attr("id", "id_" + prefix + "-" + i + "-" + name);
                });
                i = i + 1;
            });
            return false;
        }
    </script>



    <script>
        $(document).ready(function () {

            $('div.hide_phone').hide();

            $('div.phone').each(function () {
                $(this).find('a.remove').click(function () {
                    return delete_form(this, 'phone');
                })
            });

            $('div.hide_phone').each(function () {
                $(this).find('a.remove').click(function () {
                    return delete_form(this, 'phone');
                })
            });

            $('a.phone').click(function () {
                return add_form('phone');
            })
        })
    </script>
{% endblock %}